const express = require('express');
const historialPlaceCotroller = require('../controllers/HistorialPlaceController');
const historicalPlaceRouter = express.Router();
let path='/historicalPlaces';
historicalPlaceRouter.get(path+'/create', historialPlaceCotroller.historical_place_create_get);
historicalPlaceRouter.get(path+'/', historialPlaceCotroller.historical_place_index);
historicalPlaceRouter.post(path+'/', historialPlaceCotroller.historical_place_create_post);
historicalPlaceRouter.get(path+'/:id', historialPlaceCotroller.historical_place_details);
historicalPlaceRouter.delete(path+'/:id',historialPlaceCotroller.historical_place_delete);
historicalPlaceRouter.put(path+'/:id',historialPlaceCotroller.historical_place_update);
module.exports = historicalPlaceRouter;
